spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/train_booking
    username: train_admin
    password: train_password
    driver-class-name: org.postgresql.Driver



  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha